apiVersion: apps/v1
kind: Deployment
metadata:
  name: sba-payment
  namespace: sba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sba-payment
  template:
    metadata:
      labels:
        app: sba-payment
    spec:
      containers:
        - name: sba-payment
          image: registry.cn-chengdu.aliyuncs.com/zhangh/sba-payment:{version}
          ports:
            - name: http-port
              containerPort: 9995
          env:
            - name: spring_profiles_active
              value: k8s
      imagePullSecrets:
        - name: sba